### ISSUE TITLE
Slow convergence speed

### ISSUE THREAD

**Issue by Originlightwkp** [LHCyGan/Fairmot#1]
Hello, I have applied your improvement to Fairmot's object detection and found that compared to the original model, your improvement resulted in slow model convergence, with the loss convergence speed of hm, wh, and reg much slower than expected. I used vanb3 for a single rtx3090 experiment.

**Comment by Originlightwkp** [comment]
now，i have try vanb1.

**Comment by LHCyGan** [comment]
A good attempt, the VAN of the current parameters does converge slowly

**Comment by LHCyGan** [comment]
VAN can bring improvement on MOT17-val
